name: dbbconnect
services:
    postgres:
        image: postgres:17
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}',
                ]
            interval: 10s
            timeout: 5s
            retries: 5
        expose:
            - '5432'

    # backend:
    #     build:
    #         context: ./backend
    #     restart: unless-stopped
    #     env_file:
    #         - .env
    #     environment:
    #         NODE_ENV: production
    #         PORT: '8098'
    #         DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    #     depends_on:
    #         postgres:
    #             condition: service_healthy
    #     ports:
    #         - '127.0.0.1:8099:8098'

    backend:
        image: ghcr.io/chowjustin/dbbconnect:latest
        restart: unless-stopped
        env_file:
            - .env
        environment:
            NODE_ENV: production
            PORT: '8098'
            DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - '127.0.0.1:8099:8098'

volumes:
    pgdata:
